forum/urls.py
from django.urls import path
from forum import views

app_name = 'forum'

urlpatterns = [
    path('', views.home, name='home'),
    path('classes/', views.ClassListView.as_view(), name='class_list'),
    path('classes/<int:pk>/', views.ClassDetailView.as_view(), name='class_detail'),
    # path('classes/create/', views.ClassCreateView.as_view(), name='class_create'),
    path('classes/delete/<int:pk>/', views.ClassDeleteView.as_view(), name='class_delete'),
    path('classes/update/<int:pk>/', views.ClassUpdateView.as_view(), name='class_update'),
    # path('classes/questions/<int:pk>/', views.QuestionCreateView.as_view(), name='question_create'),
    path('classes/question/detail/<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('classes/question/update/<int:pk>/', views.QuestionUpdateView.as_view(), name='question_update'),
    path('classes/question/delete/<int:pk>/', views.QuestionDeleteView.as_view(), name='question_delete'),
    # path('classes/answer/<int:pk>/', views.AnswerCreateView.as_view(), name="answer_create"),
    path('classes/answer/<int:pk>/delete/', views.AnswerDeleteView.as_view(), name="answer_delete"),
    path('classes/answer/<int:pk>/update/', views.AnswerUpdateView.as_view(), name="answer_update"),
    path('classes/answer/<int:pk>/detail/', views.AnswerDetailView.as_view(), name="answer_detail"),
    # path('classes/answer/reply/<int:pk>/', views.ReplyCreateView.as_view(), name="reply_create"),
    path('classes/answer/reply/<int:pk>/delete/', views.ReplyDeleteView.as_view(), name="reply_delete"),
    path('classes/answer/reply/<int:pk>/update/', views.ReplyUpdateView.as_view(), name="reply_update"),
    # path('class/join/', views.join_class, name='join')
    path('classes/question/<slug:operation>/<int:pk>', views.vote_question, name='vote')
]

stu_teach/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('forum.urls')),
    path('account/', include('registration_redux.backends.default.urls')),
    path('', views.landing_page, name='landing_page'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    # path('class/', include('forum.join_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'stu_teach.views.error_404'
handler500 = 'stu_teach.views.error_500'
handler400 = 'stu_teach.views.error_400'
handler403 = 'stu_teach.views.error_403'

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from .random_class_code import random_string_generator


class Class(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='class_set')
    created_at = models.DateTimeField(auto_now_add=True)
    class_avatar = models.ImageField(upload_to='class_image', default='class_image/class_cover.jpg')
    students = models.ManyToManyField(User, related_name='class_student')
    code = models.CharField(max_length=12, blank=True)

    def get_absolute_url(self):
        return reverse('forum:class_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


@receiver(post_save, sender=Class)
def save_class_code(sender, **kwargs):
    if kwargs['created']:
        code = random_string_generator()
        class_object = Class.objects.get(pk=kwargs['instance'].pk)
        qs_exists = Class.objects.filter(code=code).exists()
        if qs_exists:
            code = random_string_generator()
            return save_class_code(sender, **kwargs)
        class_object.code = code
        class_object.save()


class Question(models.Model):
    title = models.CharField(max_length=255)
    instruction = models.TextField(blank=True)  # TODO decide to make instruction optional or not
    class_room = models.ForeignKey(Class, on_delete=models.CASCADE, related_name='question_set')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='question_set')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    votes = models.IntegerField(default=0)
    upvoted_by = models.ManyToManyField(User, related_name='question_upvoted')
    downvoted_by = models.ManyToManyField(User, related_name='question_downvoted')
    files = models.FileField(upload_to='question_files', blank=True)

    def get_absolute_url(self):
        return reverse('forum:class_detail', kwargs={'pk': self.class_room.pk})  # TODO use question detail view

    def __str__(self):
        return self.title


class Answer(models.Model):
    body = models.TextField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answer_set')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='answer_set')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    votes = models.IntegerField(default=0)
    upvoted_by = models.ManyToManyField(User, related_name='answer_upvoted')
    downvoted_by = models.ManyToManyField(User, related_name='answer_downvoted')
    files = models.FileField(upload_to='answer_files', blank=True)

    def get_absolute_url(self):
        return reverse('forum:question_detail', kwargs={'pk': self.question.pk})


class Reply(models.Model):
    body = models.TextField()
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name="reply_set")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reply_set")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    """Reaction todo"""  # TODO

    def get_absolute_url(self):
        return reverse('forum:answer_detail', kwargs={'pk': self.answer.pk})

forum/forms.py
from .models import Class, Question, Answer, Reply
from django.forms import ModelForm
from django import forms


class ClassCreateForm(ModelForm):
    class Meta:
        model = Class
        fields = ['name', 'description', 'class_avatar', ]


class QuestionCreateForm(ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'instruction', 'files', ]


class AnswerCreateForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['body', 'files']


class ReplyCreateForm(ModelForm):
    class Meta:
        model = Reply
        fields = ['body', ]


class JoinForm(forms.Form):
    code = forms.CharField()


class DeleteForm(forms.Form):
    pass

forum/views.py
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView, TemplateView
from .models import Class, Question, Answer, Reply
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from .forms import (
    ClassCreateForm, QuestionCreateForm, AnswerCreateForm, ReplyCreateForm, JoinForm, DeleteForm
)
from django.contrib.auth.models import User
from django.http import JsonResponse


# class ClassListView(ListView):
#     model = Class
#     context_object_name = 'classes'
#     template_name = 'forum/class_list.html'


class ClassListView(TemplateView):
    template_name = 'forum/class_list.html'

    def get(self, request, *args, **kwargs):
        form = ClassCreateForm()
        classes = Class.objects.all()
        args = {'form': form, 'classes': classes}
        return render(request, self.template_name, args)

    def post(self, request, *args, **kwargs):
        form = ClassCreateForm(request.POST)
        try:
            if form.is_valid():
                classs = form.save(commit=False)
                classs.created_by = request.user
                classs.save()
                messages.success(request, 'Class created successfully.')
                return redirect('forum:class_detail', pk=classs.pk)

        except Exception as e:
            messages.warning(request, "Failed To Create. Error: {}".format(e))
        messages.warning(request, "Failed To Create Check Errors")
        classes = Class.objects.all()
        args = {'form': form, 'classes': classes}
        return render(request, self.template_name, args)

# class ClassCreateView(CreateView):
#     model = Class
#     # Either use form class or fields
#     fields = ['name', 'description', 'class_avatar', ]
#     template_name = 'forum/class_create.html'
#
#     def form_valid(self, form):
#         form.instance.created_by = self.request.user
#         return super().form_valid(form)


# class ClassDetailView(DetailView):
#     model = Class
#     context_object_name = 'class'
#     template_name = 'forum/class_detail.html'


class ClassDetailView(TemplateView):
    template_name = 'forum/class_detail.html'

    def get(self, request, *args, **kwargs):
        form = QuestionCreateForm()
        single_class = get_object_or_404(Class, pk=self.kwargs['pk'])
        questions = single_class.question_set.order_by('-votes')
        args = {'form': form, 'class': single_class, 'questions': questions}
        return render(request, self.template_name, args)

    def post(self, request, *args, **kwargs):
        form = QuestionCreateForm(request.POST)
        class_pk = self.kwargs['pk']
        if form.is_valid():
            questions = form.save(commit=False)
            questions.created_by = User.objects.get(pk=request.user.pk)
            questions.class_room = Class.objects.get(pk=class_pk)
            questions.save()

            return redirect('forum:class_detail', pk=class_pk)

        args = {'form': form}
        return render(request, self.template_name, args)


class ClassDeleteView(DeleteView):
    model = Class
    success_url = reverse_lazy('forum:class_list')

#
# class QuestionCreateView(CreateView):
#     model = Question
#     fields = ['title', 'instruction', 'files', ]
#     template_name = 'forum/question_create.html'
#
#     def form_valid(self, form):
#         form.instance.created_by = self.request.user
#         form.instance.class_room = Class.objects.get(pk=self.kwargs['pk'])
#         return super().form_valid(form)

#
# class QuestionDetailView(DetailView):
#     model = Question
#     template_name = 'forum/question_detail.html'


class QuestionDetailView(TemplateView):
    template_name = 'forum/question_detail.html'

    def get(self, request, *args, **kwargs):
        form = AnswerCreateForm()
        question = get_object_or_404(Question, pk=self.kwargs['pk'])
        args = {'form': form, 'question': question}
        return render(request, self.template_name, args)

    def post(self, request, *args, **kwargs):
        form = AnswerCreateForm(request.POST)
        class_pk = self.kwargs['pk']
        if form.is_valid():
            question_pk = self.kwargs['pk']
            answer = form.save(commit=False)
            answer.created_by = User.objects.get(pk=request.user.pk)
            answer.question = Question.objects.get(pk=question_pk)
            answer.save()

            return redirect('forum:question_detail', pk=class_pk)

        args = {'form': form}
        return render(request, self.template_name, args)


class QuestionUpdateView(UpdateView):
    model = Question
    fields = ['title', 'instruction', ]
    template_name = 'forum/question_update.html'


class QuestionDeleteView(DeleteView):
    model = Question

    def get_success_url(self):
        return reverse_lazy('forum:class_detail', kwargs={'pk': self.get_object().class_room.pk})


class ClassUpdateView(UpdateView):
    model = Class
    template_name = 'forum/class_update.html'
    fields = fields = ['name', 'description', 'class_avatar',]

#
# def home(request):
#     return render(request, 'forum/home.html', {'user': request.user, })


# class AnswerCreateView(CreateView):
#     model = Answer
#     fields = ['body', 'files']
#     template_name = 'forum/reply_create.html'
#
#     def form_valid(self, form):
#         form.instance.created_by = self.request.user
#         form.instance.question = Question.objects.get(pk=self.kwargs['pk'])
#         return super().form_valid(form)

#
# class AnswerDetailView(DetailView):
#     model = Answer
#     template_name = 'forum/answer_detail.html'


class AnswerDetailView(DetailView):
    template_name = 'forum/answer_detail.html'

    def get(self, request, *args, **kwargs):
        form = ReplyCreateForm()
        answer = get_object_or_404(Answer, pk=self.kwargs['pk'])
        args = {'form': form, 'answer': answer}
        return render(request, self.template_name, args)

    def post(self, request, *args, **kwargs):
        form = ReplyCreateForm(request.POST)
        answer_pk = self.kwargs['pk']
        if form.is_valid():
            question_pk = self.kwargs['pk']
            reply = form.save(commit=False)
            reply.created_by = request.user
            reply.answer = Answer.objects.get(pk=answer_pk)
            reply.save()

            return redirect('forum:answer_detail', pk=answer_pk)

        args = {'form': form}
        return render(request, self.template_name, args)


class AnswerUpdateView(UpdateView):
    model = Answer
    fields = ['body', 'files', ]
    template_name = 'forum/answer_update.html'


class AnswerDeleteView(DeleteView):
    model = Answer

    def get_success_url(self):
        return reverse_lazy('forum:question_detail', kwargs={'pk': self.get_object().question.pk})


# class ReplyCreateView(CreateView):
#     model = Reply
#     fields = ['body',]
#     template_name = 'forum/reply_create.html'
#
#     def form_valid(self, form):
#         form.instance.created_by = self.request.user
#         form.instance.answer = Answer.objects.get(pk=self.kwargs['pk'])
#         return super().form_valid(form)


class ReplyUpdateView(UpdateView):
    model = Reply
    fields = ['body', ]
    template_name = 'forum/reply_update.html'


class ReplyDeleteView(DeleteView):
    model = Reply

    def get_success_url(self):
        return reverse_lazy('forum:answer_detail', kwargs={'pk': self.get_object().answer.pk})


def home(request):
    joined_classes = Class.objects.filter(students=request.user).order_by('-created_at')
    started_classes = Class.objects.filter(created_by=request.user).order_by('-created_at')

    j_page = request.GET.get('j_page', 1)
    j_paginator = Paginator(joined_classes, 4)
    s_page = request.GET.get('s_page', 1)
    s_paginator = Paginator(started_classes, 4)
    try:
        joined_classes = j_paginator.page(j_page)
        started_classes = s_paginator.page(s_page)
    except PageNotAnInteger:
        joined_classes = j_paginator.page(1)
        started_classes = s_paginator.page(1)
    except EmptyPage:
        joined_classes = j_paginator.page(j_paginator.num_pages)
        started_classes = s_paginator.page(s_paginator.num_pages)
    joined_classes.page_url_label = 'j_page'
    started_classes.page_url_label = 's_page'

    if request.method == 'POST':
        j_form = JoinForm(request.POST)
        c_form = ClassCreateForm(request.POST, request.FILES)
        del_form = DeleteForm(request.POST)

        if j_form and j_form.is_valid():
            code = j_form.cleaned_data['code']
            try:
                class_object = Class.objects.get(code=code)
                if class_object:
                    class_object.students.add(request.user)
                    class_pk = class_object.pk
                    messages.success(request, 'Welcome to Class')
                    return redirect('forum:class_detail', pk=class_pk)
            except Class.DoesNotExist:
                pass
            c_form = ClassCreateForm()
            del_form = DeleteForm()
            messages.warning(request, 'No class Found. Enter the correct invitation code.')
            return render(request, 'forum/home.html', {
                'j_form': j_form,
                's_classes': started_classes,
                'j_classes': joined_classes,
                'c_form': c_form,
                'del_form': del_form,
            })
        elif c_form and c_form.is_valid():
            try:
                classs = c_form.save(commit=False)
                classs.created_by = request.user
                classs.save()
                messages.success(request, 'Class created successfully.')
                return redirect('forum:class_detail', pk=classs.pk)
            except Exception as e:

forum/templates/forum/answer_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Answer deletion{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure want to delete " {{ question }} "?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

forum/templates/forum/answer_create.html
{% extends 'base.html' %}

{% block title %}Create Answer{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
{% endblock %}

forum/templates/forum/answer_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="carousel-inner">
    <div class="item active">
      <img class="image" src="{{ answer.question.class_room.class_avatar.url }}" alt="Class Avatar">

        <div class="hero">
            <h1 data-heading="{{ answer.question.class_room.name }}">{{ class.name }}</h1>
            <p class="text-block-footer col-sm-9"><span>{{ answer.question.class_room.description }}</span></p>
            <figcaption><img class="profileUser" src="{{ answer.question.class_room.created_by.profile.get_avatar_url }}" alt="{{ class.created_by.get_fullname }}" class="profile" style="border-radius: 50%;" /></figcaption>
            <div class="text-block">
            {% if request.user == answer.question.class_room.created_by %}Class Code: {{ answer.question.class_room.code }}{% endif %}
            <p>Teacher: <a href="{% url 'view_others_profile' pk=answer.question.class_room.created_by.pk %}">{{ answer.question.class_room.created_by }}</a>
                {% if request.user == answer.question.class_room.created_by %}    <br><a href="{% url 'forum:class_update' pk=answer.question.class_room.pk %}">Edit</a>|
                <a href="{% url 'forum:class_delete' pk=answer.question.class_room.pk %}">Delete</a></p>{% endif %}
            </div>
        </div>
    </div>
 </div><br>
<div class="container main-section border">
            <div class="col-lg-12 col-sm-12 col-12">
                <div class="row">
        <div class="col-lg-2 col-sm-2 col-5">
            <img src="{{ answer.created_by.profile.get_avatar_url }}" class="circular--landscape" width="150px">
        </div>
        <div class="col-lg-10 col-sm-10 col-7">
          <p>
            {{ answer.body }}<br>
            {% if answer.files %}<a href="{{ answer.files.url }}">Attached Files</a>{% endif %}

          </p>
        </div>
      </div>
      <div class="row post-detail">
        <div class="col-lg-12 col-sm-12 col-12">
            <ul class="list-inline">
              <li class="list-inline-item">
                <img src="https://dummyimage.com/20x20/a8a1a8/0f0f12" class="rounded-circle" width="20px"> <span>by</span> <span class="text-info">{{ answer.created_by.username }}</span>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-calendar" aria-hidden="true"></i> <span>{{ answer.created_at.date  }}</span>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-share-square-o" aria-hidden="true"></i> <span class="text-info">{{ answer.reply_set.count }} Replies</span>
                 {% if request.user == answer.created_by %}
                      <a href="{% url 'forum:answer_update' pk=answer.pk %}">Edit</a>|
                  <a href="{% url 'forum:answer_delete' pk=answer.pk %}">Delete</a>
                  {% endif %}
              </li>
            </ul>
        </div>
      </div>
    </div>
  </div>
    <!-- Trigger the modal with a button -->
<button type="button" class="button button1" data-toggle="modal" data-target="#myModal">Reply Here</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
          <h3 class="modal-title">Reply</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'form-template.html' %}
            <button class="button button1">Create</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div><br>
    Replies:<br>
    {% for reply in answer.reply_set.all %}
        <div class="container main-section border">
            <div class="col-lg-12 col-sm-12 col-12">
                <div class="row">
        <div class="col-lg-2 col-sm-2 col-5">
            <img src="{{ reply.created_by.profile.get_avatar_url }}" class="circular--landscape" width="150px">
        </div>
        <div class="col-lg-10 col-sm-10 col-7">
          <p>
            {{ reply.body }}
          </p>
        </div>
      </div>
      <div class="row post-detail">
        <div class="col-lg-12 col-sm-12 col-12">
            <ul class="list-inline">
              <li class="list-inline-item">
                <img src="https://dummyimage.com/20x20/a8a1a8/0f0f12" class="rounded-circle" width="20px"> <span>by</span> <span class="text-info">{{ answer.created_by.username }}</span>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-calendar" aria-hidden="true"></i> <span>{{ reply.created_at.date  }}</span>
              </li>
              <li class="list-inline-item">
                  {% if request.user == reply.created_by %}
                      <a href="{% url 'forum:reply_update' pk=reply.pk %}">Edit</a>|
                      <a href="{% url 'forum:reply_delete' pk=reply.pk %}">Delete</a>
                  {% endif %}
              </li>
            </ul>
        </div>
      </div>
    </div>
  </div><hr>

    {% endfor %}
{% endblock %}

forum/templates/forum/question_detail.html
{% extends 'base.html' %}
{% block content %}
{#    <h1>{{ question.title }}</h1>#}
{#    <p>Class room: {{ question.class_room.name }}</p>#}
{#    <p>Instruction: {{ question.instruction }}</p>#}
{#    <p>{% if question.files %}<a href="{{ question.files.url }}">Get files here.</a>{% endif %}</p>#}
{#    <small>Question By: {{ question.created_by.get_full_name }} {{ question.created_at.date }}</small>#}
{#    <a href="{% url 'forum:question_update' pk=question.pk %}">Edit</a>|#}
{#    <a href="{% url 'forum:question_delete' pk=question.pk %}">Delete</a>#}
{#    <hr>#}
    <div class="carousel-inner">
    <div class="item active">
      <img class="image" src="{{ question.class_room.class_avatar.url }}" alt="Class Avatar">

        <div class="hero">
            <h1 data-heading="{{ question.class_room.name }}">{{ class.name }}</h1>
            <p class="text-block-footer col-sm-9"><span>{{ question.class_room.description }}</span></p>
            <figcaption><img class="profileUser" src="{{ question.class_room.created_by.profile.get_avatar_url }}" alt="{{ class.created_by.get_fullname }}" class="profile" style="border-radius: 50%;" /></figcaption>
            <div class="text-block">
            {% if request.user == question.class_room.created_by %}Class Code: {{ question.class_room.code }}{% endif %}
            <p>Teacher: <a href="{% url 'view_others_profile' pk=question.class_room.created_by.pk %}">{{ question.class_room.created_by }}</a>
                {% if request.user == question.class_room.created_by %}<br><a href="{% url 'forum:class_update' pk=question.class_room.pk %}">Edit</a>|
                <a href="{% url 'forum:class_delete' pk=question.class_room.pk %}">Delete</a></p>{% endif %}
            </div>
        </div>
    </div>
 </div>
    <hr>
         <div class="container main-section border">
            <div class="col-lg-12 col-sm-12 col-12">
                <div class="row">
                    <div class="col-md-1">
                  <br>
                        <a href="{% url 'forum:vote' operation='upvote' pk=question.pk %}" class="upvote"><span class="fa fa-chevron-up {% if request.user in question.upvoted_by.all %}active{% endif %}"></span></a><br>
                    <b id="votes_count{{ question.id }}">{{question.votes}}</b><br>
                  <a href="{% url 'forum:vote' operation='downvote' pk=question.pk %}" class="downvote"><span class="fa fa-chevron-down {% if request.user in question.downvoted_by.all %}active{% endif %}"></span></a>
                </div>
        <div class="col-lg-2 col-sm-2 col-5">
            <img src="{{ question.created_by.profile.get_avatar_url }}" class="circular--landscape" width="150px">
        </div>
        <div class="col-lg-9 col-sm-9 col-6">
          <h4 class="text-primary">{{ question.title }}</h4>
          <p>
            {{ question.instruction }}
          </p>
        </div>
      </div>
      <div class="row post-detail">
        <div class="col-lg-12 col-sm-12 col-12">
            <ul class="list-inline">
              <li class="list-inline-item">
                <img src="https://dummyimage.com/20x20/a8a1a8/0f0f12" class="rounded-circle" width="20px"> <span>by</span> <span class="text-info">{{ question.created_by.username }}</span>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-calendar" aria-hidden="true"></i> <span>{{ question.created_at.date  }}</span>
              </li>

              <li class="list-inline-item">
                <i class="fa fa-share-square-o" aria-hidden="true"></i> <span class="text-info">{{ question.answer_set.count }} Answers</span>
                   {% if request.user == question.created_by %}
                      <a href="{% url 'forum:question_update' pk=question.pk %}"><span class="text-info">Edit</span></a>|
                      <a href="{% url 'forum:question_delete' pk=question.pk %}"><span class="text-info">Delete</span></a>
                  {% endif %}
              </li>
            </ul>
        </div>
      </div>
    </div>
  </div>

        <!-- Trigger the modal with a button -->
<button type="button" class="button button1" data-toggle="modal" data-target="#myModal">Answer Here</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
          <h3 class="modal-title">Answer</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'form-template.html' %}
            <button class="button button1">Create</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
    <h2>Answers:</h2>
    {% for answer in question.answer_set.all %}


        <div class="container main-section border">
            <div class="col-lg-12 col-sm-12 col-12">
                <div class="row">
        <div class="col-lg-2 col-sm-2 col-5">
            <img src="{{ answer.created_by.profile.get_avatar_url }}" class="circular--landscape" width="150px">
        </div>
        <div class="col-lg-10 col-sm-10 col-7">
          <p>
            {{ answer.body }}<br>
            {% if answer.files %}<a href="{{ answer.files.url }}">Attached Files</a>{% endif %}

          </p>
        </div>
      </div>
      <div class="row post-detail">
        <div class="col-lg-12 col-sm-12 col-12">
            <ul class="list-inline">
              <li class="list-inline-item">
                <img src="https://dummyimage.com/20x20/a8a1a8/0f0f12" class="rounded-circle" width="20px"> <span>by</span> <span class="text-info">{{ answer.created_by.username }}</span>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-calendar" aria-hidden="true"></i> <span>{{ answer.created_at.date  }}</span>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-comment" aria-hidden="true"></i><a href="{% url 'forum:answer_detail' pk=answer.pk %}"><span class="text-info">Reply</span></a>
              </li>
              <li class="list-inline-item">
                <i class="fa fa-share-square-o" aria-hidden="true"></i> <span class="text-info">{{ answer.reply_set.count }} Replies</span>
                  {% if request.user == answer.created_by %}
                      <a href="{% url 'forum:answer_update' pk=answer.pk %}">Edit</a>|
                  <a href="{% url 'forum:answer_delete' pk=answer.pk %}">Delete</a>
                  {% endif %}
              </li>
            </ul>
        </div>
      </div>
    </div>
  </div><hr>


    {% endfor %}
{% endblock %}