forum/urls.py
from django.urls import path
from forum import views

app_name = 'forum'

urlpatterns = [
    path('', views.home, name='home'),
    path('classes/', views.ClassListView.as_view(), name='class_list'),
    path('classes/<int:pk>/', views.ClassDetailView.as_view(), name='class_detail'),
    # path('classes/create/', views.ClassCreateView.as_view(), name='class_create'),
    path('classes/delete/<int:pk>/', views.ClassDeleteView.as_view(), name='class_delete'),
    path('classes/update/<int:pk>/', views.ClassUpdateView.as_view(), name='class_update'),
    # path('classes/questions/<int:pk>/', views.QuestionCreateView.as_view(), name='question_create'),
    path('classes/question/detail/<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('classes/question/update/<int:pk>/', views.QuestionUpdateView.as_view(), name='question_update'),
    path('classes/question/delete/<int:pk>/', views.QuestionDeleteView.as_view(), name='question_delete'),
    # path('classes/answer/<int:pk>/', views.AnswerCreateView.as_view(), name="answer_create"),
    path('classes/answer/<int:pk>/delete/', views.AnswerDeleteView.as_view(), name="answer_delete"),
    path('classes/answer/<int:pk>/update/', views.AnswerUpdateView.as_view(), name="answer_update"),
    path('classes/answer/<int:pk>/detail/', views.AnswerDetailView.as_view(), name="answer_detail"),
    # path('classes/answer/reply/<int:pk>/', views.ReplyCreateView.as_view(), name="reply_create"),
    path('classes/answer/reply/<int:pk>/delete/', views.ReplyDeleteView.as_view(), name="reply_delete"),
    path('classes/answer/reply/<int:pk>/update/', views.ReplyUpdateView.as_view(), name="reply_update"),
    # path('class/join/', views.join_class, name='join')
    path('classes/question/<slug:operation>/<int:pk>', views.vote_question, name='vote')
]

stu_teach/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('forum.urls')),
    path('account/', include('registration_redux.backends.default.urls')),
    path('', views.landing_page, name='landing_page'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    # path('class/', include('forum.join_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'stu_teach.views.error_404'
handler500 = 'stu_teach.views.error_500'
handler400 = 'stu_teach.views.error_400'
handler403 = 'stu_teach.views.error_403'

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}STU-TEACH{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'stu_teach/styles.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/typicons/2.0.7/typicons.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <script src="{% static 'js/vote.js' %}"></script>
    {%block css%}{%endblock%}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="container-fluid">

        <a href="{% url 'landing_page' %}" class="navbar-brand" style="font-family: 'Peralta', cursive;">STU-TEACH</a>

        <button  type="button" class="navbar-toggler" data-toggle="collapse" data-target="#myID">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="myID">
            {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link link-1" href="{% url 'forum:home' %}"><span class="fa fa-home"></span> Home</a> </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle link-1" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{{ request.user.profile.get_avatar_url }}" height="35px" width="35px" style="border-radius: 50%">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                            <label class="dropdown-item" href="#"> {{ request.user.username }}<span class="fa fa-cog"></span> </label>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'view_self_profile' %}"><span class="fa fa-user-o"></span> Profile</a>
                            <a class="dropdown-item" href="{% url 'auth_password_change' %}">Change password</a>
                            <a class="dropdown-item" href="{% url 'edit_profile' %}">Edit Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'auth_logout' %}"><span class="fa fa-sign-out"></span> Log out</a>
                        </div>
                    </li>
                </ul>


            {% else %}
                <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link link-1" href="{% url 'registration_register' %}">Register</a> </li>
                <li class="nav-item"><a class="nav-link link-1" href="{% url 'auth_login' %}"><span class="fa fa-sign-in"></span> Login</a> </li>
                <li class="nav-item"><a class="nav-link link-1" href="{% url 'auth_password_reset' %}"><span class="typcn typcn-refresh"></span> Reset Password</a> </li>
                </ul>
            {% endif %}

        </div>

    </div>
</nav>
{% block content %}
{% endblock %}
{% block body %}
{% endblock %}
<footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h5>STU-TEACH© 2018</h5></div>
            </div>
        </div>
</footer>
</body>
{%block script%}{%endblock%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/notify.min.js' %}"></script>
</html>

templates/error_400.html
{% extends 'base.html' %}

{% block content %}
    <h1>Nai Nai 400 error aayo</h1>

    <a href="{% url 'forum:home' %}">Return to home</a>
{% endblock %}

templates/error_403.html
{% extends 'base.html' %}

{% block content %}
    <h1>Nai nai 403 error aayo</h1>
    <a href="{% url 'forum:home' %}">Return to home</a>
{% endblock %}

templates/error_404.html
{% extends 'base.html' %}

{% block content %}
    <h1>Oops! 404</h1>
    <a href="{% url 'forum:home' %}">Return to home</a>
{% endblock %}

templates/error_500.html
{% extends 'base.html' %}

{% block content %}
    <h1>Internal Server Error 500 nai nai nai</h1>
    <a href="{% url 'forum:home' %}">Return to home</a>
{% endblock %}

templates/form-template.html
{% load widget_tweaks %}
{% load form_tags %}
{% if form.non_field_errors %}
     <div class="alert alert-danger" role="alert">
     {% for error in form.non_field_errors %}
         <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
     {% endfor %}
     </div>
{% endif %}
{% if error_message %}
  {{error_message}}
{% endif %}
{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        {% if field|is_file_field %}
            {{ field }}
        {% else %}
            {% if form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field field class="form-control" %}
            {% endif %}
            {% if field.help_text %}
                <small class="form-text">
                    {{ field.help_text | safe }}
                </small>
            {% endif %}
        {% endif %}
    </div>
{% endfor %}

templates/paginator_template.html
{% if list.has_other_pages %}
    <nav aria-label="Lists pagination" class="mb-4">
      <ul class="pagination">
        {% if list.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?{% if list.page_url_label %}{{ list.page_url_label }}{% else %}page{% endif %}={{ list.previous_page_number }}">Previous</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <span class="page-link">Previous</span>
          </li>
        {% endif %}

        {% for page_num in list.paginator.page_range %}
          {% if list.number == page_num %}
            <li class="page-item active">
              <span class="page-link">
                {{ page_num }}
                <span class="sr-only">(current)</span>
              </span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?{% if list.page_url_label %}{{ list.page_url_label }}{% else %}page{% endif %}={{ page_num }}">{{ page_num }}</a>
            </li>
          {% endif %}
        {% endfor %}

        {% if list.has_next %}
          <li class="page-item">
            <a class="page-link" href="?{% if list.page_url_label %}{{ list.page_url_label }}{% else %}page{% endif %}={{ list.next_page_number }}">Next</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <span class="page-link">Next</span>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}